/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Leowald (https://sketchfab.com/leovvald)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bored-witch-c5071e07e01a4d6294dbdbeb9428e03c
Title: Bored Witch
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Witch(props) {
  const { nodes, materials } = useGLTF('/background/proff.png')

  const modelRef = useRef()


  useFrame((state,delta,XRFrame)=>{
modelRef.current.position.y = -0.6+Math.sin(state.clock.elapsedTime)*0.10;

  })

  return (
    <group {...props} dispose={null}
    ref={modelRef}
    position={[0,-1.5,0]}
    scale={[0.6,0.6,0.6]}
    rotation={[0.05,0,0]}
    
    
    >
        
    
    </group>
  )
}

useGLTF.preload('/background/proff.png')
