/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Leowald (https://sketchfab.com/leovvald)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bored-witch-c5071e07e01a4d6294dbdbeb9428e03c
Title: Bored Witch
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Witch(props) {
  const { nodes, materials } = useGLTF('models/witch-transformed.glb')

  const modelRef = useRef()


  useFrame((state,delta,XRFrame)=>{
modelRef.current.position.y = -0.6+Math.sin(state.clock.elapsedTime)*0.10;

  })

  return (
    <group {...props} dispose={null}
    ref={modelRef}
    position={[-0.5,-1.5,0]}
    scale={[0.6,0.6,0.6]}
    rotation={[0.05,0,0]}
    
    
    >
        
      <mesh
        name="Object_4"
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
        position={[0.751, 0.243, 3.666]}
        rotation={[0.019, 0.268, -0.138]}
        scale={[1, 0.043, 0.564]}
      />
      <mesh
        name="Object_14"
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.Peau}
        position={[0.876, 2.42, 1.098]}
        rotation={[0.765, 0.425, -0.57]}
        scale={1.52}
      />
    </group>
  )
}

useGLTF.preload('models/scene-transformed.glb')
